###
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "firstName": "Jack",
    "lastName": "rade",
    "email": "mama@gmail.com",
    "password": "KOTkot2020"
}
###
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "mama@gmail.com",
    "password": "KOTkot2020"
}

